### ISSUE TITLE
Why are invalid parameters reported?

### ISSUE THREAD

**Issue by linux-gcc** [inclavare-containers/inclavare-containers#1522] opened 2021-12-08 02:07 UTC
Running the hello_world program in the docker+rune+occlum scenario reports the following error:
failed to kill: EINVAL (#22, Invalid argument): invalid arguments [line = 354, file = src/entry.rs]
[ERROR] occlum-pal: Failed to occlum_ecall_kill:  EINVAL (line 226, file src/pal_api.c)

**Comment by hustliyilin** [comment] 2021-12-08 03:34
> Running the hello_world program in the docker+rune+occlum scenario reports the following error: failed to kill: EINVAL (#22, Invalid argument): invalid arguments [line = 354, file = src/entry.rs] [ERROR] occlum-pal: Failed to occlum_ecall_kill: EINVAL (line 226, file src/pal_api.c)

Could you provide more Environment information, such as the version of your `OS`、`SGX`、`sgxsdk`、`Occlum`(both `host` and `docker` image)，and `rune`？ Thanks. @linux-gcc

**Comment by linux-gcc** [comment] 2021-12-08 05:56
OS：centos 8.2
SGX driver: 2.11.0
SGXSDK: 2.14.100.2.
occlum: 0.25.0
rune: 0.6.3-1

@hustliyilin

**Comment by haosanzi** [comment] 2021-12-08 06:52
@linux-gcc Could you please use occlum version 0.21.0？ Currently, `rune` is compatible with occlum 0.21.0 and will adapt to the higher version of occlum version in the future. 
Please add `-e ENCLAVE_RUNTIME_LOGLEVEL="debug"` to the `docker run` command  to use debug mode

**Comment by hustliyilin** [comment] 2021-12-08 10:33
> @linux-gcc Could you please use occlum version 0.21.0？ Currently, `rune` is compatible with occlum 0.21.0 and will adapt to the higher version of occlum version in the future. Please add `-e ENCLAVE_RUNTIME_LOGLEVEL="debug"` to the `docker run` command to use debug mode

@linux-gcc Please follow the guide of @haosanzi .  Beside, If you add `-e ENCLAVE_RUNTIME_LOGLEVEL="debug"` to the `docker run` command to use debug mode, you can also the log in the `/run/containerd/io.containerd.runtime.v1.linux/moby/${container-id}/log.json`, thanks.

**Comment by linux-gcc** [comment] 2021-12-09 01:16
The first version used was occlum 0.21, and occlum 0.21 would also report the same error. In addition, I traced the code. The value of the signal passed when the error occurred was -1. Where is this signal usually sent from? Why is this signal value -1?
thanks!

**Comment by hustliyilin** [comment] 2021-12-09 02:57
> The first version used was occlum 0.21, and occlum 0.21 would also report the same error. In addition, I traced the code. The value of the signal passed when the error occurred was -1. Where is this signal usually sent from? Why is this signal value -1? thanks!

@linux-gcc The first version used was occlum 0.25 rather than occlum 0.21 because the error you provided:
- invalid arguments [line = 354, file = src/entry.rs] ：because the line number of [occlum 0.25.0 entry.rs](https://github.com/occlum/occlum/blob/0.25.0/src/libos/src/entry.rs)  is `354` while the line number of [occlum 0.21.0 entry.rs ](https://github.com/occlum/occlum/blob/0.21.0/src/libos/src/entry.rs) is `321`.
- occlum-pal: Failed to occlum_ecall_kill: EINVAL (line 226, file src/pal_api.c): because the line number of [occlum 0.25.0 pal_api.c](https://github.com/occlum/occlum/blob/0.25.0/src/pal/src/pal_api.c)  is `226` while the line number of [occlum 0.21.0 pal_api.c ](https://github.com/occlum/occlum/blob/0.21.0/src/pal/src/pal_api.c) is `213`.


So you need to run `docker + run + occlum` in the occlum `0.21.0` docker image and you also need to ensure the `occlum_pal` version(`ls -l /opt/occlum/build/lib/libocclum-pal.so`) in your host is `0.21.0`.

**Comment by linux-gcc** [comment] 2021-12-09 04:03
The above log is based on occlum 0.25. I mean that the same error will be reported when occlum 0.21 is used at the beginning, and then occlum is replaced with version 0.25. Since the log of occlum 0.21 was not saved before, the log of 0.25 currently used was uploaded.
In addition, the ENCLAVE_RUNTIME_LOGLEVEL="debug" parameter seems to only output the debug log of occlum? Didn't see rune's debug log?

**Comment by hustliyilin** [comment] 2021-12-09 04:39
> The above log is based on occlum 0.25. I mean that the same error will be reported when occlum 0.21 is used at the beginning, and then occlum is replaced with version 0.25. Since the log of occlum 0.21 was not saved before, the log of 0.25 currently used was uploaded. In addition, the ENCLAVE_RUNTIME_LOGLEVEL="debug" parameter seems to only output the debug log of occlum? Didn't see rune's debug log?

@linux-gcc `occlum` is only one of enclave runtime of `rune`, and `rune` currently is only compatible with `occlum 0.21.0` and doesn't adapt to the higher version of occlum version. 
- So it's better to change to use `occlum 0.21.0` : As far as I know, the higher version of `occlum` and the lower version is not compatible, and maybe `occlum.json` has changed. It is recommended to use a consistent `occlum` version to build and run confidential container images
-  you should check whether you environment is ok or not: 
please run   the  `sgxsdk SampleCode/SampleEnclave` and `occlum run` firstly

As for the debug log of `rune`, `rune` log is outputed to the corresponding Docker container log（`/run/containerd/io.containerd.runtime.v1.linux/moby/${container-id}/log.json`）, If you can't see your `docker container` log, you may not see the rune's log.

**Comment by linux-gcc** [comment] 2021-12-09 06:20
1.sgxsdk SampleCode/SampleEnclave and occlum run are running normally. 
2.Based on the 0.25 occlum version, an error will also be reported. The log is as follows:
 [ INFO][T0][#0] Process created: elf = /bin/init, pid = 1
[ERROR][T1][#3][····Open] Error = ENOENT (#2, No such file or directory): EntryNotFound
[2021-12-09T14:06:30.273Z][ERROR][T1][#4][····Open] Error = ENOENT (#2, No such file or directory): EntryNotFound
[ INFO][T1][#39][ExitGroup] Thread exited: tid = 1, status = 0
[ WARN][T0][#39][ExitGroup] HostFS: sync is unimplemented
failed to kill: EINVAL (#22, Invalid argument): invalid arguments [line = 321, file = src/entry.rs]
[ERROR] occlum-pal: Failed to occlum_ecall_kill: EINVAL (line 213, file src/pal_api.c)

**Comment by haosanzi** [comment] 2021-12-09 06:30
@linux-gcc Could you provide the Dockfile used to build the occlum image and the full parameters of your `docker run` command?

**Comment by linux-gcc** [comment] 2021-12-09 08:08
1.dockerfile:

FROM centos:8.2.2004

RUN mkdir -p /run/rune
WORKDIR /run/rune

ADD occlum_instance_hello.tar.gz /run/rune

ENTRYPOINT ["/bin/hello_world"]

2. full parameters:
docker run -it --rm --runtime=rune -e ENCLAVE_TYPE=intelSgx -e ENCLAVE_RUNTIME_PATH=/opt/occlum/build/lib/libocclum-pal.so -e ENCLAVE_RUNTIME_ARGS=occlum_instance_hello occlum-app-hello

**Comment by haosanzi** [comment] 2021-12-10 13:51
@linux-gcc  Hi, I have made a reference image, could you please run the following command in your machine?
```shell
docker run -it --rm --runtime=rune   \
  -e ENCLAVE_TYPE=intelSgx   \
  -e ENCLAVE_RUNTIME_PATH=/opt/occlum/build/lib/libocclum-pal.so   \
  -e ENCLAVE_RUNTIME_ARGS=occlum_instance \
  haosanzi/occlum-hello:0.21.0
```

**Comment by linux-gcc** [comment] 2021-12-13 01:10
sgx machine is not connected to the Internet, can you directly send the image file?

thanks!
@haosanzi

**Comment by haosanzi** [comment] 2021-12-13 02:28
@linux-gcc Yes. Can you provide me with the communication method, so that I can send the image to you?

**Comment by linux-gcc** [comment] 2021-12-13 02:51
Can I upload image files directly through github attachments?
thanks !

**Comment by haosanzi** [comment] 2021-12-13 03:05
The tar of the image file can Not uploaded as GitHub attachments. Can you find a machine that is connected to the Internet, download the image file then pass to your sgx machine?

**Comment by linux-gcc** [comment] 2021-12-13 03:55
1.If you use the mirror file you provided, the same error will be reported. error info:
 
INFO][T0][#0] Process created: elf = /bin/init, pid = 1
[ERROR][T1][#3][····Open] Error = ENOENT (#2, No such file or directory): EntryNotFound
[ERROR][T1][#4][····Open] Error = ENOENT (#2, No such file or directory): EntryNotFound
[ INFO][T1][#39][ExitGroup] Thread exited: tid = 1, status = 0
[ WARN][T0][#39][ExitGroup] HostFS: sync is unimplemented
failed to kill: EINVAL (#22, Invalid argument): invalid arguments [line = 321, file = src/entry.rs]
[ERROR] occlum-pal: Failed to occlum_ecall_kill: EINVAL (line 213, file src/pal_api.c)
[ INFO][T0][#0] Process created: elf = /bin/hello_world, pid = 2

2.How can I debug this error now? The value of the signal passed when the error occurred was -1. Where is this signal usually sent from? Why is this signal value -1?

**Comment by linux-gcc** [comment] 2021-12-13 03:55
1.If you use the mirror file you provided, the same error will be reported. error info:
 
INFO][T0][#0] Process created: elf = /bin/init, pid = 1
[ERROR][T1][#3][····Open] Error = ENOENT (#2, No such file or directory): EntryNotFound
[ERROR][T1][#4][····Open] Error = ENOENT (#2, No such file or directory): EntryNotFound
[ INFO][T1][#39][ExitGroup] Thread exited: tid = 1, status = 0
[ WARN][T0][#39][ExitGroup] HostFS: sync is unimplemented
failed to kill: EINVAL (#22, Invalid argument): invalid arguments [line = 321, file = src/entry.rs]
[ERROR] occlum-pal: Failed to occlum_ecall_kill: EINVAL (line 213, file src/pal_api.c)
[ INFO][T0][#0] Process created: elf = /bin/hello_world, pid = 2

2.How can I debug this error now? The value of the signal passed when the error occurred was -1. Where is this signal usually sent from? Why is this signal value -1?

**Comment by hustliyilin** [comment] 2021-12-13 04:20
> sgx machine is not connected to the Internet, can you directly send the image file?
> 
> thanks! @haosanzi

If your machine isn't connected to the Internet. How do you download the `occlum` image and install `rune` and `occlum-pal` components？ @linux-gcc

**Comment by haosanzi** [comment] 2021-12-13 05:35
@linux-gcc About question 1, the image provided by my is running successfully in both SGX1 and SGx2 machines according to my test.  Could you please check your occlum version again? I ask the occlum team, the error of `[ERROR][T1][#3][····Open] Error = ENOENT (#2, No such file or directory): EntryNotFound` may be caused by the wrong Occlum version. The confidential image I provided was built by occlum 0.21.0, and there is no init program in it. But occlum 0.25.0 needs the init process, so an error about ENOENT  will be reported.

About question 2, If you want to debug rune + occlum, rune itself is also a command-line tool, you can convert your docker image into OCI bundle, refer to this [guide](https://github.com/alibaba/inclavare-containers/tree/master/rune#creating-an-oci-bundle) to debug your OCI bundle (rune --debug run test).  rune, like runc, is the runtime of docker. So if you want to use Docker to run and debug, you need to debug docker and view docker logs, which is relatively complicated, as we said above. It is recommended to use oci bundle for debugging.  I am not quite sure what is the reason for the signal value -1. Please refer to the above debugging method to see if you can get more detailed error information.

**Comment by linux-gcc** [comment] 2021-12-13 06:35
> download the image file then pass to your sgx machine

i download rune and occlum-pal from the other machine then pass to the sgx machine

**Comment by linux-gcc** [comment] 2021-12-13 06:37
> download the image file then pass to your sgx machine

i download rune and occlum-pal from the other machine then pass to the sgx machine

**Comment by linux-gcc** [comment] 2021-12-13 07:38
> @linux-gcc About question 1, the image provided by me is running successfully in both SGX1 and SGx2 machines according to my test. Could you please check your occlum version again? I ask the occlum team, the error of `[ERROR][T1][#3][····Open] Error = ENOENT (#2, No such file or directory): EntryNotFound` may be caused by the wrong Occlum version. The confidential image I provided was built by occlum 0.21.0, and there is no init program in it. But occlum 0.25.0 needs the init process, so an error about ENOENT will be reported.


First of all, I run the image file (including the one you provided and the one I made) will have "hello world" output. I am just curious why the following error is reported:
failed to kill: EINVAL (#22, Invalid argument): invalid arguments [line = 321, file = src/entry.rs]
[ERROR] occlum-pal: Failed to occlum_ecall_kill: EINVAL (line 213, file src/pal_api.c)

Second, judging from the code corresponding to the log above, my occlum version should be 0.21. If it is 0.25 version of occlum, run the corresponding mirror file, there will be "hello world" output, and the corresponding log is reported as follows:
  failed to kill: EINVAL (#22, Invalid argument): invalid arguments [line = 354, file = src/entry.rs]
[ERROR] occlum-pal: Failed to occlum_ecall_kill: EINVAL (line 226, file src/pal_api.c)

**Comment by haosanzi** [comment] 2021-12-13 07:59
@linux-gcc Sorry, I thought you did not see the output of hello world. The solutions provided above is to enable you to run hello world quickly.

This error is okay. Because the Inclavare containers supports occlum is designed like this: the original runc as the runtime, its essence is just to enter the runc process in the container's namespace, and then execve to become the real app, so all the signals sent to the container were actually sent to this app. As for rune, if you want to be compatible with this semantics, it becomes all signals sent to rune must pass through the pal API defined between runelet and occlum pal, call occlum's pal API in the form of a function call to forward this signal, and then occlum converts this forwarding into a signal notification mechanism inside occlum.

So the errors you see are that rune received the signal sent from the host, and then forwarded it to occlum, but occlum did not recognize or did not implement the corresponding signal processing and printed errors.

I wonder if this explanation is clearer?

**Comment by hustliyilin** [comment] 2021-12-13 08:01
> First of all, I run the image file (including the one you provided and the one I made) will have "hello world" output. I am just curious why the following error is reported:

Why don't you give all of your log information at the beginning, but only a part of it?  @linux-gcc  This is occlum log, you can add `-e ENCLAVE_RUNTIME_LOGLEVEL="off"` to close it.

From [Occlum github](https://github.com/occlum/occlum#how-to-debug), occlum set the default value of `OCCLUM_LOG_LEVEL` is `off`

![image](https://user-images.githubusercontent.com/6824093/145773918-416e79e7-a5fc-4659-ba40-4145bbd0c23d.png)

**Comment by linux-gcc** [comment] 2021-12-13 09:38
> Sorry, I thought you did not see the output of hello world. The solutions provided above is to enable you to run hello world quickly.
> 
> This error is okay. Because the Inclavare containers supports occlum is designed like this: the original runc as the runtime, its essence is just to enter the runc process in the container's namespace, and then execve to become the real app, so all the signals sent to the container were actually sent to this app. As for rune, if you want to be compatible with this semantics, it becomes all signals sent to rune must pass through the pal API defined between runelet and occlum pal, call occlum's pal API in the form of a function call to forward this signal, and then occlum converts this forwarding into a signal notification mechanism inside occlum.
> 
> So the errors you see are that rune received the signal sent from the host, and then forwarded it to occlum, but occlum did not recognize or did not implement the corresponding signal processing and printed errors.

I probably understand your explanation. I still have a few questions:
1. Which signals are currently supported by occlum? Are there occlum-related design documents?
2. When an error occurs, the signal value seems to be -1. Under what conditions does the inclavare container usually generate the -1 signal? Is there a design document for inclavare container?
3. Since occlum does not currently support processing certain signals, can we optimize the inclavare container or occlum? For example: filter some signals in the inclavare container? Or adjust the log level in occlum, and only report warning logs when encountering a signal that is not currently supported?
4. I think there is a /bin/init file in the image file, why does occlum report the following error:
ERROR][T1][#3][····Open] Error = ENOENT (#2, No such file or directory): EntryNotFound

thanks !

**Comment by haosanzi** [comment] 2021-12-13 09:47
@linux-gcc  Some questions are about occlum, please go to the Occlum community to [raise an issue](https://github.com/occlum/occlum/issues).  Thank you!

**Comment by hustliyilin** [comment] 2021-12-13 10:45
> > Sorry, I thought you did not see the output of hello world. The solutions provided above is to enable you to run hello world quickly.
> > This error is okay. Because the Inclavare containers supports occlum is designed like this: the original runc as the runtime, its essence is just to enter the runc process in the container's namespace, and then execve to become the real app, so all the signals sent to the container were actually sent to this app. As for rune, if you want to be compatible with this semantics, it becomes all signals sent to rune must pass through the pal API defined between runelet and occlum pal, call occlum's pal API in the form of a function call to forward this signal, and then occlum converts this forwarding into a signal notification mechanism inside occlum.
> > So the errors you see are that rune received the signal sent from the host, and then forwarded it to occlum, but occlum did not recognize or did not implement the corresponding signal processing and printed errors.
> 
> I probably understand your explanation. I still have a few questions:
> 
> 1. Which signals are currently supported by occlum? Are there occlum-related design documents?
> 2. When an error occurs, the signal value seems to be -1. Under what conditions does the inclavare container usually generate the -1 signal? Is there a design document for inclavare container?
> 3. Since occlum does not currently support processing certain signals, can we optimize the inclavare container or occlum? For example: filter some signals in the inclavare container? Or adjust the log level in occlum, and only report warning logs when encountering a signal that is not currently supported?
> 4. I think there is a /bin/init file in the image file, why does occlum report the following error:
>    ERROR][T1][[Many documents for Architecture and design details needed！ #3](https://github.com/alibaba/inclavare-containers/issues/3)][····Open] Error = ENOENT ([Could you provide a example #2](https://github.com/alibaba/inclavare-containers/issues/2), No such file or directory): EntryNotFound
> 
> thanks !

If you open `OCCLUM_LOG_LEVEL` to run `occlum` without `rune`,  it may have the same problem. @linux-gcc So It's a question
about occlum rather than `inclavare-containers`, so please go to the Occlum community to [open an issue](https://github.com/occlum/occlum/issues). Thank you!

**Comment by linux-gcc** [comment] 2021-12-13 11:33
I will ask questions about occlum in the occlum community. Can you answer the following two questions:
1、 I open OCCLUM_LOG_LEVEL to run occlum without rune ，The following problems will not occur：
failed to kill: EINVAL (# 22, Invalid argument): invalid arguments [line = 321, file = src/entry.rs]
[ERROR] occlum-pal: Failed to occlum_ecall_kill: EINVAL (line 213, file src/pal_api.c)
2、When an error occurs, the signal value seems to be -1. Under what conditions does the inclavare container usually generate the -1 signal? Is there a design document for inclavare container?

thanks!

**Comment by hustliyilin** [comment] 2021-12-13 11:46
> 1、 I open OCCLUM_LOG_LEVEL to run occlum without rune ，The following problems will not occur：
> failed to kill: EINVAL (# 22, Invalid argument): invalid arguments [line = 321, file = src/entry.rs]
> [ERROR] occlum-pal: Failed to occlum_ecall_kill: EINVAL (line 213, file src/pal_api.c)

@linux-gcc Inclavare Containers can be deployed with Occlum LibOS, `[WebAssembly Micro Runtime (WAMR)](https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/product-mini/platforms/linux-sgx/enclave-sample/App#wamr-as-an-enclave-runtime-for-rune)`, and `[skeleton](https://github.com/bytecodealliance/wasm-micro-runtime/tree/main/product-mini/platforms/linux-sgx/enclave-sample/App#wamr-as-an-enclave-runtime-for-rune)`. So If you run other enclave runtimes, it wouldn't be the error.

**Comment by hustliyilin** [comment] 2021-12-13 11:52
![image](https://user-images.githubusercontent.com/6824093/145807092-2caaafbf-8c60-457a-abcc-f68326cd9eb6.png)

**Comment by hustliyilin** [comment] 2021-12-13 12:13
```shell
export OCCLUM_LOG_LEVEL=info
occlum init
occlum build
occlum run /bin/hello_world
```

there are many errors in `occlum run` according to the steps.

![image](https://user-images.githubusercontent.com/6824093/145809822-4f12545d-ade0-424d-b71c-cb2bfdfa3940.png)


As for the signal, you need to run `docker + runc + occlum` to see whether it exists or not. @linux-gcc

**Comment by linux-gcc** [comment] 2021-12-14 00:52
1、yes, This error exists，And I said this issue before, I will consult the occlum community。
[ERROR][T1][#  3][····Open] Error = ENOENT (#  2, No such file or directory): EntryNotFound
[ERROR][T1][#  3][····Open] Error = ENOENT (#  2, No such file or directory): EntryNotFound
2、I mean, when running occlum run /bin/hello_world alone, the following errors exist. But when running with docker+rune+occlum, the following errors will exist. I want to know the logic of rune sending signals? Why is a signal with a value of -1 being sent?
failed to kill: EINVAL (# 22, Invalid argument): invalid arguments [line = 321, file = src/entry.rs]
[ERROR] occlum-pal: Failed to occlum_ecall_kill: EINVAL (line 213, file src/pal_api.c)

**Comment by linux-gcc** [comment] 2021-12-14 00:52
1、yes, This error exists，And I said this issue before, I will consult the occlum community。
[ERROR][T1][#  3][····Open] Error = ENOENT (#  2, No such file or directory): EntryNotFound
[ERROR][T1][#  3][····Open] Error = ENOENT (#  2, No such file or directory): EntryNotFound
2、I mean, when running occlum run /bin/hello_world alone, the following errors exist. But when running with docker+rune+occlum, the following errors will exist. I want to know the logic of rune sending signals? Why is a signal with a value of -1 being sent?
failed to kill: EINVAL (# 22, Invalid argument): invalid arguments [line = 321, file = src/entry.rs]
[ERROR] occlum-pal: Failed to occlum_ecall_kill: EINVAL (line 213, file src/pal_api.c)

**Comment by hustliyilin** [comment] 2021-12-14 03:02
1.  Occlum is only one of enclave runtime of `rune`, there are many enclave  runtimes rune supported, such as `skeleton` and `WAMR`.  In other enclave runtimes, this signal error doesn't exist.  So the signal is defined by the corresponding enclave runtime.  Even in occlum,  this error couldn't  affect the correctness of the running program, So the problem's priority is not high.

![image](https://user-images.githubusercontent.com/6824093/145924781-c900a53a-49c7-4254-88cd-7b9184c713d9.png)



2. Inclavare containers include `rune`、`shim-rune`、`sgx-tools`、`epm`、`inclavared`、`shelter`、`verdicted`、`rats-tls`、`enclave-tls` and etc.   

![image](https://user-images.githubusercontent.com/6824093/145924821-16916b5a-09b0-494b-85a8-b3ca6bd053af.png)


We have many things to do currently, and I think you are very serious and responsible @linux-gcc . We hope that you will participate in the co-construction of the community, including but not limited to locating and resolving this signal issue you opened

**Comment by haosanzi** [comment] 2021-12-14 07:02
@linux-gcc About the logic of rune sending signals and signal -1, please refer to [link](https://github.com/alibaba/inclavare-containers/blob/master/rune/libenclave/internal/runtime/pal/spec_v2.md#5pal_kill) for more infomation.

```
@pid: Send to all processes if equal to -1, or send to current process if equal to 0, or send to the process that owns the pid if others.  
@sig: Signal number to be sent.
```

**Comment by jiazhang0** [comment] 2022-03-04 00:29
@linux-gcc If you have any questions, you could reopen this issue.

**Closed by jiazhang0** 2022-03-04 00:29 UTC
Labels: question, low
